### ISSUE TITLE
The models for deep lima should not be required when deep lima is not used

### ISSUE THREAD

**Issue by romaricb** [aymara/lima#104]
The models for deep lima should not be required when deep lima is not used: e.g. when TensorFlow is not available, the eng.ud submodules should not be necessary.

**Comment by kleag** [comment]
This is not really the models here. The submodule allows to obtain the English EWT corpus from Universal Dependencies to be able to train the SVMTool-based PoS tagger for the UD-based classic LIMA. 
But anyway, it should no be mandatory.

**Comment by victorbocharov** [comment]
I cannot reproduce this problem.

```./gbuild.sh -m Debug|Release -p OFF -T``` passes successfully. tva also passes without errors in debug and release modes.

**Comment by romaricb** [comment]
OK. I was missing the -T option. Thank you for your answer.
