### ISSUE TITLE
Allow to use deep lima languages with the same options as standard LIMA

### ISSUE THREAD

**Issue by kleag** [aymara/lima#105]
**Describe the bug**
Currently, deep LIMA languages are usable only with analyzeText with the following syntax:
```bash
$ analyzeText -l ud -p deepud --opts udlang:eng your-text-file.txt
```
They are not usable with LIMA server nor the lima GUI.

**Expected behavior**
The standard syntax should automatically select ud "language", deepud pipeline and `udlang:<lang>` opts when the given language is not supported. For example:
```bash
$ analyzeText -l bre your-text-file.txt
```
should be equivalent to:
analyzeText -l ud -p deepud --opts udlang:bre your-text-file.txt
```

To select deep version for English while eng is the standard implementation, a fake deepeng language should be added to deepud configuration.

**Comment by victorbocharov** [comment]
Partially fixed by https://github.com/aymara/lima/commit/55ea423f38d35b0a92106ed0b4fdcd136c05acab and https://github.com/aymara/lima/commit/b2d1612ee3065b47538e7dc6f8ed4bd5094a8f47 :

```
# For UD models with deepud pipeline and Breton language
$ analyzeText -l bre your-text-file.txt
```

```
# For rule-based pipeline main and English language
$ analyzeText -l eng your-text-file.txt
```

```
# For UD models with deepud pipeline and English language
$ analyzeText -l ud-eng your-text-file.txt
```

**Comment by victorbocharov** [comment]
Partially fixed for LIMA GUI:

- all available models are loaded during initialization (no lazy loading yet)
- all existing languages are added to configs in form "ud-$langcode"

Can consume 100+ Gb of RAM if all models are downloaded.

Remaining subtasks:

- lazy loading of models
- dynamic update of comboboxes: languages and pipelines (normally not all languages are available and not all language/pipeline combinations are possible)
- LIMA server

**Comment by victorbocharov** [comment]
LIMA server supports UD models (all languages mentioned in `lima_linguisticprocessing/conf/lima-server.xml`).
Lazy loading is turned on by default in LIMA server and LIMA GUI.
analyzeText doesn't use lazy loading because it can cause the analyzer to fail in the middle of the analysis process in case of the misconfiguration. With normal loading procedure the error will appear sooner.

**Comment by victorbocharov** [comment]
Looks like everything is done.

**Comment by kleag** [comment]
Thank you!
