### ISSUE TITLE
Need coherence within SpecificEntitiesModex , AnalysisGraph , PosGraph and Dumpers

### ISSUE THREAD

**Issue by benlabbe** [aymara/lima#106]
I am facing a problem in the context of Specific Entity Recognition with a rule-based modex.

Thanks to @romaricb I can provide a code sample.
[test-affiliation2.zip](https://github.com/aymara/lima/files/5261362/test-affiliation2.zip)

**Describe the bug**

The test.sh script in the archive compiles a .rules file and configures a TestModex for Specific Entity Recognition.
The rules are simple. They are based on the t_capital token type.
The "main" pipeline executes the TestModex as well as several usual processUnits : SpecificEntitiesModex, SvmToolPosTagger, sentenceBoundariesFinder, conllDumper, and bratDumper .

The test.txt sample document contains patterns to be identities as TEST.AFFILIATION entity, and also general entities being Person.PERSON, Datetime.DATE, etc.

The problem arises when I start to mix the ProcessUnit , order and the configurations for TestModex and the bratDumper.

* If I change the SvmToolPosTagger for the viterbiPostagger-freq , the pipeline crashes. 
```
Analyzing 1/1 (100.00%) 'test.txt' : LP::Segmentation : 2020-09-22T14:41:44.012 ERROR 0x55a73d8d4e30 Error: cannot find position of begin vertex  14  for segmentation data
```

* I cannot see both the TEST.AFFILIATION and Person.PERSON Entities in the brat dumped file test.ann . 
  * If TestModex is after the SvmToolPosTagger and sentenceBoundariesFinder, the detected entities are saved in the PosGraph, and so has to be configured the bratDumper to read the PosGraph in order to dump the TEST.AFFILIATION detections. But the PERSON and DATE entities are then not found by the bratDumper. Only the conllDumper finds them since it crawls both the graphs.
  * If TestModex is before the SvmToolPosTagger and sentenceBoundariesFinder, then I will not be able to use the CLIMA generated rules for semantic relations finding co-occurring entities inside sentences.
  * If I configure the bratDumper to read the AnalysisGraph , then I don't find the TEST.AFFILIATION detections in the test.ann dumped file.

NB : the "domain" configuration in the bratDumper is left empty to allow the display of all the entities from all domains.
NB2 : There are some offset errors while displaying the whole sentence in the conllDumper. The first character is omitted.

**Expected behaviour**

I would like to find both the  TEST.AFFILIATION and Person.PERSON Entities in the brat dumped file test.ann, even though the two modex where executed on to distinct graphs.
The conllDumper seems to behave properly as it prints systematically all the entities.
 
@kleag  @victorbocharov  @romaricb  ??

**Comment by kleag** [comment]
I suppose the Brat dumper should be corrected to behave like the conll dumper by exploring both graphs. @romaricb , do you agree?

**Comment by benlabbe** [comment]
Thank you @kleag . Did you manage to reproduce the described behaviour ?

**Comment by kleag** [comment]
Not yet. My comment was a guess after reading your description

**Comment by romaricb** [comment]
The current behaviour of the bratDumper is to look only at the graph given as argument. It could indeed be modified to also look at the AnalysisGraph when the PosGraph is given. I'm not sure if it should be a forced default behavior or something controlled by a parameter.
Possible workarounds include : 
- setting the "followGraph"  parameter to false in the bratDumper -> all the entities found in whichever step are  printed
- putting everything before the postagger, including a specific SentenceBoundaries unit so that the sentence restriction will work.

**Comment by kleag** [comment]
>  I'm not sure if it should be a forced default behavior

Is there any argument against that?

**Comment by romaricb** [comment]
> > I'm not sure if it should be a forced default behavior
> 
> Is there any argument against that?

since you can specify the graph on which you want to work, it seems reasonable to work only on this graph...

**Comment by victorbocharov** [comment]
@benlabbe 

> If I change the SvmToolPosTagger for the viterbiPostagger-freq , the pipeline crashes.

It seems that doesn't crash any more since 19b50a5f80d00f1a6db64a6d942728d5f5d672e5
Please check on your side.

**Comment by victorbocharov** [comment]
> The problem arises when I start to mix the ProcessUnit , order ...

Modex PU update graph by removing the old nodes and inserting the new ones. It doesn't update segmentation. This can result in a mismatch between the graph and segmentation. Finally, it gives errors in later stages: conllDumper fails in case it can't find vertices mentioned in SentenceBoundaries as begin or end. There are several workarounds:

1. create SentenceBoundaries just before the PU that needs them. Thus you can be sure that boundaries are correct.
Example:
TensorFlowSpecificEntities requires boundaries and these boundaries are created by sentenceBoundariesFinderForSE. These boundaries aren't used by any other module later. For conllDumper, the newer version is created later by sentenceBoundariesFinder.

2. set useSentenceBounds=no in Modex config
useSentenceBounds=yes with several sequential Modex modules can lead to strange results that could be difficult to explain: the first Modex removes sentence begin/end vertex and the following treats two sentences as one. 
Example:
All NER modules: none of them uses SentenceBoundaries.

3. use SentenceBoundariesUpdater after Modex. It merges several sentences in case their boundary vertices are removed. This protects only from exceptions in conllDumper.

**Comment by victorbocharov** [comment]
@benlabbe to what extent this problem still exists?

**Comment by benlabbe** [comment]
Thank-you all.
I reorganized my pipeline according to your advise.
My workflow is now operational.

I am currently testing the implementation of Romaric c803030f9cdf expanding the Brat Dumper to display both types of entities (in AnaGraph and in PosGraph)
