### ISSUE TITLE
Entities splitted in ner-deep

### ISSUE THREAD

**Issue by romaricb** [aymara/lima#110]
The entities found by the ner-deep pipeline are not properly updated in the analysis graph. The update may create a sequence of entities with the same type instead of a single entity. The bug is not visible with the ConllDumperNer (I guess the BIO encoding makes some arrangements there).
This is a problem if the entities are to be used further in the pipeline, other than produced as output by the conllDumperNer.

Example:

```SOCIÉTÉ FRANÇAISE DE RECHERCHES ET D’INVESTISSEMENTS SFRI SA```

The output of the conllDumperNer is 
```
SOCIÉTÉ NC I-NP B-Organization.ORGANIZATION
FRANÇAISE ADJ I-NP I-Organization.ORGANIZATION
DE P I-NP I-Organization.ORGANIZATION
RECHERCHES NC I-NP I-Organization.ORGANIZATION
ET CC I-NP I-Organization.ORGANIZATION
D’INVESTISSEMENTS PONCT I-NP I-Organization.ORGANIZATION
SFRI NPP I-NP I-Organization.ORGANIZATION
SA NPP I-NP I-Organization.ORGANIZATION
```
which indicates a single entity found.
In fact, the analysis graph has 3 entities: here with the BratDumper
```
T1      ORGANIZATION 0 34       SOCIÉTÉ FRANÇAISE DE RECHERCHES ET
T2      ORGANIZATION 35 52      D’INVESTISSEMENTS
T3      ORGANIZATION 53 60      SFRI SA
```
This internal structure is confirmed by the SpecificEntitiesXmlLogger or the DotGraphWriter.

**Comment by victorbocharov** [comment]
Looks like the bug on ConllDumper level. Now works like this:

```
SOCIÉTÉ NC I-NP B-Organization.ORGANIZATION
FRANÇAISE ADJ I-NP I-Organization.ORGANIZATION
DE P I-NP I-Organization.ORGANIZATION
RECHERCHES NC I-NP I-Organization.ORGANIZATION
ET CC I-NP I-Organization.ORGANIZATION
D’INVESTISSEMENTS PONCT I-NP B-Organization.ORGANIZATION
SFRI NPP I-NP B-Organization.ORGANIZATION
SA NPP I-NP I-Organization.ORGANIZATION
```

**Comment by romaricb** [comment]
OK for the correction, the behavior is now consistent (even if not really satisfactory with regards to the quality of the NE detection).
