### ISSUE TITLE
Due to pricing changes at Travis, we should migrate CI to Github Actions

### ISSUE THREAD

**Issue by kleag** [aymara/lima#111]
Reference:
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
https://docs.travis-ci.com/user/migrate/open-source-repository-migration/#frequently-asked-questions

Information to migrate:
https://developer.okta.com/blog/2020/05/18/travis-ci-to-github-actions

Work has started on:
https://github.com/aymara/lima/tree/github-actions-test

**Comment by kleag** [comment]
Interesting experience of a kde based project migrating to github actions:
https://euroquis.nl//calamares/2021/02/02/cala-infrastructure.html

One of its recipes:
https://github.com/calamares/calamares/blob/calamares/.github/workflows/ci-neon.yml

**Comment by victorbocharov** [comment]
As a temporary solution I've added Dockerfile-travis-ubuntu20.04 (one of the build methods we used on Travis) to Appveyor.

**Comment by victorbocharov** [comment]
The deployment of Debian packages from Appveyor added.

**Comment by kleag** [comment]
Appveyor works great. Thanks. But I think that we should be able to use Github Actions though. Currently it works but deployment of releases don't. 
So, I keep this issue open but as a wish instead of a general problem.

**Comment by kleag** [comment]
I changed my mind: Appveyor works greatly currently. It does the job. So we can stay with it. 
@all: don't hesitate to reopen if you think I'm wrong.
