### ISSUE TITLE
log4cpp is broken

### ISSUE THREAD

**Issue by kleag** [aymara/lima#112]
The distributed log4cpp configuration is broken. No output is generated. Signaled by @romaricb and confirmed by me.

There is two problems with workarounds:

- No appender is defined by default. Workaround: uncomment the following line to append messages to stderr: ```log4j.appender.DebugOutput=```
- Categories defined in subfolders (while read; this is visible when `log4j.category.FilesReporting=INFO` is defined in the root file) are not active even if set to `DEBUG`. Workaround: integrate all categories from subfolders to the root file. This one can be in a user-defined folder using `$LIMA_CONF`.

**Comment by kleag** [comment]
Commits c565487f96bae1b4e22a252616b5f2a535c80cee and a60f2d24079c0a73cf3ad45af729c357e508d888 should correct this bug.
One activates the appender to stderr and the other remove the duplicate lima common appenders in lp that were overwriting changes made in the lima common file.

@romaricb, please confirm it corrects the problem for you too and close this issue if it is the case.

**Comment by romaricb** [comment]
Thanks, the commits correct the problem.
However, all the files in the $LIMA_CONF/log4cpp/ directory are used and this may cause problem if there are non-relevant files (I had the examples of emacs backup files such as `limalp.log.properties~` that are read and used). A filter should be added to only read files with extension `.properties`.

**Comment by kleag** [comment]
Only `*.properties` files are loaded now.
Furthermore, commit 31a5770e8a574a66dcc21e6e8767649d245cbc33 improves loggers defaults and allow to finely debug loggers. Now if the root category `Logging` is set to default, the categories definitions overwriting previous ones are printed with the concerned files.
