### ISSUE TITLE
TF-based lemmatizer forgets a trace of its execution

### ISSUE THREAD

**Issue by kleag** [aymara/lima#114]
When using the tensorflow-based lemmatizer, a spurious trace file is left behind. This `lemmatizer.cache` is created there:
https://github.com/aymara/lima/blob/57628dcfa331bfb0a60030aa2cff8ff915b5dff9/lima_linguisticprocessing/src/linguisticProcessing/core/TensorFlowUnits/Lemmatizer/Lemmatizer.cpp#L1209

Should it be just removed? If not, it should at least be a temporary file created using QTemporaryFile or stored in a dedicated location. 

In fact, it seems to be related to the `load_cache` mechanism in the same file but which is working on another path.

**Comment by victorbocharov** [comment]
This logic would be better to be replaced by normal dictionaries. Does LIMA have a method to find a lemma by form + grammatical features?
