### ISSUE TITLE
[LIMA GUI] allow to build LIMA without the GUI

### ISSUE THREAD

**Issue by benlabbe** [aymara/lima#117]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I compile LIMA but the desired usage is behind a web-service , or even for an integration into Amose.
In those use-case, the compilation of LIMA with its GUI is not relevant. When you add the integration of the web-service inside a container, then the GUI compilation makes no sense while it adds dependencies and adds many Mo to the compile docker images.

**Describe the solution you'd like**
My solution is to insert a compilation mode of LIMA , such as a command-line parameter to **gbuild.sh**, to deactivate the GUI compilation.

Any comment from the dev team ?
@victorbocharov ?
@kleag ?
@romaricb ?
@jtourille ?

Rock-paper-scissor to choose who is gonna implement this: .....

**Comment by benlabbe** [comment]
rock

**Comment by kleag** [comment]
Does it take so much place and time ? The only dependency it has is Qt which is already a dependency of the remaining. 
We could save a few megabytes and a few seconds of build but is it worth the effort ?

**Comment by benlabbe** [comment]
If we don't want to build with lima_gui, we can then build without the following packages:
        - mesa-common-dev 
        - libgl1-mesa-dev 
        - libglu1-mesa-dev 
        - qml-module-qt-labs-folderlistmodel 
        - qml-module-qt-labs-settings 
Don't forget their dependencies : xserver etc.
This is a huge gain when we need only lima as a library in another application or in a webservice

**Comment by kleag** [comment]
OK then. But let's make it not the default. I want that default builds/packages of lima are usable for the normal human being,
 e.g. a linguist under Windows.

**Comment by benlabbe** [comment]
"let's make it not the default." yes,  that's the way I implemented it.

**Comment by benlabbe** [comment]
Dammit, it is effectively impossible to install Qt5 from apt without libxbc (the C binding to X). This means that nearly nothing can be saved when trying to avoid X-server installation in a docker container complied for Lima.

Hence, the only place saved is the binary executable test_gui / lima_gui if its compilation is disabled when building a standard no-gui web-service in a docker container.

**Comment by kleag** [comment]
If tout really need to save space, you can build your own Qt and select the needed modules only.
