### ISSUE TITLE
XmlReader fails in case of XML-entities

### ISSUE THREAD

**Issue by benlabbe** [aymara/lima#126]
**Describe the bug**
We identified a problem in the parsing of XML files by `CoreXmlReaderClient` (called by `analyzeXml`). The presence of XML-entities (such as `>` or `"`) may lead to offset errors on nearby tokens . The risk increases  for (long) documents of which we do not master the content (crawled HTML pages, PDF or DOCX files transcribed in XHTML by Tika). 

**To Reproduce**
On 2021-12-03 , the `test-xmlreader` unit-test fails because of this : lima/lima_linguisticprocessing/test/test-xmlreader 

**Expected behavior**
The expected behavior is not clear for me.

The questions are :
- do we have to execute `xmllint` on the input files of `analyzeXml` , so that `xmllint` replaces the XML-entities by their equivalent markup (`>` => `&gt;` ) ?
- how do we handle the mapping of offset since this replacement leads to the insertion of 3 characters ? The end-user does not want to have its input XML file modified.

**Comment by benlabbe** [comment]
Hello,

I found a code section in `analyzeMultimediaSmlDocuemnts.cpp` that might be a good candidate for a fix :
lines [346](https://github.com/aymara/lima/blob/474198344f8ec8c732048199a1b3d9a1c775a9ee/lima_linguisticprocessing/test/analyzeMultimediaXmlDocuments.cpp#L342) and followings :
```c++
        QRegExp rx("(&[^;]*;)");
        int shift = 0;
        int indexofent = 0;

        QMap< uint64_t,uint64_t > shiftFrom;
        while ((indexofent = rx.indexIn(qtext_s, indexofent)) != -1)
        {
          int indexInResolved = indexofent-shift;
          shift += rx.cap(1).size()-1;
          shiftFrom.insert(indexInResolved, shift);
          LDEBUG << "indexofent:" << indexofent << "; indexInResolved:"
                  << indexInResolved << "; shift:" << shift;
          indexofent += rx.matchedLength();
        }
```
We could try to add the ">" sign in the RegExp . Will it be sufficient ?

**Comment by kleag** [comment]
> We could try to add the ">" sign in the RegExp . Will it be sufficient ?
Well, the regex finds occurrences in the text of sgml entites like `&amp;` and fills a shift dictionary to handle the fact that the xml parser will silently replace them by the corresponding character(s) and report offsets with this new text.
Our problem in the current issue is that it seems that the xml parser does the reverse with characters like `>`. So, we could maybe use a similar mechanism but not just change the regex.

**Comment by benlabbe** [comment]
> We could try to add the ">" sign in the RegExp . Will it be sufficient ?

Yes this was a silly idea. A bit too simple . Sorry .

**Comment by kleag** [comment]
No problem.

The following program tests if there is problems in Qt reading the characters we have problems with:
```cpp
#include <QDebug>
#include <QFile>
#include <QXmlStreamReader>

int main(int argc, char *argv[])
{
    QString xml = "<TEXT>>des entités non codées&lt;></TEXT>";

    QXmlStreamReader reader(xml);

    while (!reader.atEnd()) {
        reader.readNext();
        qDebug() << reader.name();
        if (reader.isStartElement() && reader.name() == QLatin1String("TEXT"))
          qDebug() << "TEXT:" << reader.readElementText();
    }
    if (reader.hasError()) {
      qDebug() << reader.error();
      return 1;
    }
    return 0;
}
```

Its result is:
``""
"TEXT"
TEXT: ">des entités non codées<>"
""
```
So, there is no problem with the Qt parser, except for the replacement of the entities like `&lt;` that we already handle (hopefully) correctly.

**Comment by kleag** [comment]
I think that I have found where the problem occurs:
At https://github.com/aymara/lima/blob/0620384e1d61df2a750290c28d9cad7e40b07072/lima_linguisticprocessing/src/linguisticProcessing/core/DocumentsReader/structuredDocumentXMLParser.cpp#L678,
and following, we handle the characters that can be sgml entities in the input text and insert spaces to take that into account. 

The problem is that these characters can also appear directly in the text  and then, we wrongly add these spaces.

When removing the definitions of the special characters, the errors regarding these characters disappear. But then the occurrences where entities are really present become wrong.

To be continued…

**Comment by benlabbe** [comment]
Thank you Gaël. This problem was in fact expected by @romaricb .

A potential fix appears to be quite tricky.

To be continued

**Comment by kleag** [comment]
We should probably transfer the shift dictionary to decide where to handle the special characters or not. I'll check if it is feasable.

**Comment by kleag** [comment]
> We should probably transfer the shift dictionary to decide where to handle the special characters or not. I'll check if it is feasable.

<del> I'm lost in all the various handlers. I don't find where to make the link between </del>

I finally found the link:
```
MultimediaDocumentHandler
AbstractXmlDocumentHandler
AbstractXmlAnalysisHandler <- defines m_shiftFrom
AbstractAnalysisHandler


StructuredDocumentXMLParser::characters() <- where isSpecialCharacter it taken into account (use m_specialCharacterSize)
StructuredDocumentXMLParser: m_processor is a StructuredXmlDocumentHandler
StructuredDocumentXMLParser is a AbstractReaderResource
DocumentReader m_parser: StructuredDocumentXMLParser


CoreXmlReaderClient is a  AbstractXmlReaderClient
AbstractXmlReaderClient is a AbstractProcessingClient
m_handler : AbstractXmlDocumentHandler
m_documentReader : DocumentReader
```

**Comment by kleag** [comment]
Commit 10239462 partly solves this issue by transfering the shift dictionary to the handling of special characters as stated above.

There is still xmlreader test errors, though.

**Comment by kleag** [comment]
The shift dictionary handling was fundamentally broken because it handled only a few common cases. All less frequent sgml entities were introducing shifting errors.
Commit 359bfbd798af731dec85b32df430e99339bb6497 introduces a generic and cleaner way of handling sgml entities in xml text. It allows to pass all unit tests again.

**Comment by kleag** [comment]
@benlabbe , please close after you validate that the problem is solved

**Comment by kleag** [comment]
Ping @benlabbe

**Comment by benlabbe** [comment]
the recent update of TestXmlReader is a great proof of behaviour stabilisation.
Thanks @kleag for the XmlReader evolutions and for making this specific test to pass .
