### ISSUE TITLE
Error with AnalyzeText command

### ISSUE THREAD

**Issue by FatouSow** [aymara/lima#131]
I would like to analyze .txt files with LIMA but when I try to use the command analyzeText (https://github.com/aymara/lima/wiki/LIMA-User-Manual#linguistic-processing-steps), I have a syntax error :
Here is a screenshot of the error :

![image](https://user-images.githubusercontent.com/34003621/167106730-1d792dc2-9dfc-47d3-bf69-a95943db5571.png)

**Comment by kleag** [comment]
analyzeText is an executable, that must be run from the Linux shell. In your screenshot, I see that you are in the python interactive interpreter.
Try the same command from the shell. If the environment is correctly set, it should work.

**Comment by kleag** [comment]
https://github.com/aymara/lima/wiki/Install-Linux-packages

**Comment by kleag** [comment]
@FatouSow , were you able to run analyzeText?

**Comment by FatouSow** [comment]
Yes, it works. thank you very much
