### ISSUE TITLE
Error with pipelines

### ISSUE THREAD

**Issue by sma1406** [aymara/lima#132]
When I try to use a pipeline other than main or deepud I have an internal LIMA error.

Here is a screenshot of the error :

<img width="485" alt="Capture d’écran 2022-05-07 104026" src="https://user-images.githubusercontent.com/100989186/167246571-f5a731bd-da39-4e37-8863-182e3ccbba98.png">

**Comment by kleag** [comment]
You need to define the pipeline using 2 different configuration files. This is described [here](https://github.com/aymara/lima/wiki/LIMA-Technical-Documentation#lima-configuration-files).
Please comment further is things are not clear in this documentation.

**Comment by kleag** [comment]
User has solved its issue.
