### ISSUE TITLE
Pb with the TL;DR

### ISSUE THREAD

**Issue by sfermigier** [aymara/lima#146]
The TL;DR says:

```
# Upgrading pip is fundamental in order to obtain the correct LIMA version
$ pip install --upgrade pip
$ pip install aymara==0.4.1
$ lima_models.py -l eng
$ python
>>> import aymara.lima
>>> nlp = aymara.lima.Lima("ud-eng")
>>> sentences = nlp('Hello, World!')
...
```

1) When running `pip install aymara==0.4.1`, I get: `pip install aymara==0.4.1`. Last version is `0.4.0` apparently.

2) Command `lima_models.py -l eng` is not available.

3) Running the Python snippet, I get:

```
Python 3.10.6 (main, Aug 30 2022, 04:58:14) [Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import aymara.lima
>>> nlp = aymara.lima.Lima("ud-eng")
>>> sentences = nlp('Hello, World!')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'Lima' object is not callable
```

**Comment by kleag** [comment]
I see that you are using MacOS. Unfortunately, the python bindings of LIMA are only available under Linux currently. We should be more explicit about that.
In fact we don't have a working CI of LIMA itself under MacOS. This is a subject where we would need some help.

**Comment by kleag** [comment]
Older lima python bindings were using a docker container for running lima itself. Unfortunately, it is too complex to handle for most users. I will deactivate them on pypi.

**Comment by kleag** [comment]
I have updated the TL;DR to reflect the fact that it works only under Linux. Furthermore, pip should now refuse to install LIMA under macOS. A proper macOS build is necessary.
