### ISSUE TITLE
lima_models.py bug with zho-simp

### ISSUE THREAD

**Issue by Marceau-h** [aymara/lima#161]
**Describe the bug**
Hi, I'm unable to download the zho-simp model using lima_models.py

**To Reproduce**
1. Enter the command
```bash
lima_models.py -l zho-simp
```
2. Wait and you'll get an error after dhe download

**Expected behavior**
The model to download and install, here it seems to download fine but to be unable to parse a certain value ?

**Screenshots**
![image](https://user-images.githubusercontent.com/106751184/232497304-f27ea433-7dfe-480d-99cb-3965f6b6e181.png)

**Desktop (please complete the following information):**
Official docker container, but i had the same issue on an ubuntu vm

**Additional context**
It seems to be related to the fact that it's the only lang code with a dash inside it and that there is a split on the dashes

**Comment by kleag** [comment]
I confirm this bug. This is now corrected both in lima-python (future unreleased version) and current lima in 
947e5c7. Please wait for the docker image to be built before testing.

**Comment by kleag** [comment]
Build is complete. @Marceau-h , you should be able to update your docker image and test again.

**Comment by Marceau-h** [comment]
I've tried to do a fresh install by deleting the container, the mounts and docker prune but I'm getting the exact same error, with the same lines of code. Maybe I'm doing something wrong ? Is `https://hub.docker.com/r/aymara/lima` the good image ?

**Comment by kleag** [comment]
Have you updated the image with docker pull?

**Comment by Marceau-h** [comment]
I've removed the image before creating the container again, but i'll try to docker pull when i'll be home

**Comment by kleag** [comment]
> I've removed the image before creating the container again, but i'll try to docker pull when i'll be home 

Yes, but docker rm does not cause the image to be updated from the registry on next run. Pull is mandatory.

**Comment by Marceau-h** [comment]
I've just tried it and it tells me that I have the lastest image version. It also seems on dockerhub that the imagewas updated 2 years ago for the last time, should I use another image ?

![image](https://user-images.githubusercontent.com/106751184/232565546-42495cb2-aa99-4c60-931a-8bc44ae690eb.png)

**Comment by kleag** [comment]
Yes, the aymara/lima image is outdated. 
You could `docker pull aymara/lima-ubuntu22.04` but the python code will not use it, except if you modify it.

**Comment by kleag** [comment]
Could you remind me the version of lima-python you have installed?

**Comment by Marceau-h** [comment]
Actually I'm not using the module, I have the docker on a server and I request it with [this script](https://gist.github.com/Marceau-h/7677bde7eaaaf6b676feb5ea22bca50b)

I've tried to make my own image to have the lang model installed but didn't succed yet

**Comment by Marceau-h** [comment]
Of course, this is the command that i'm using
```docker
docker run
  -d
  --name='lima2'
  --net='mhnet'
  -e TZ="Europe/Paris"
  -e HOST_CONTAINERNAME="lima2"
  -p '6668:8080/tcp' 'ghcr.io/aymara/lima:master'
```

For the address, i'm using it behind a reverse proxy, i just removed the real address from the gist

**Comment by Marceau-h** [comment]
I just tried with the github image and the lima_models script is working fine now !

**Comment by kleag** [comment]
Great !
I made your script work with the docker image above with:
```
docker run  -d -p 6668:8080 -v /home/gael/.local/share/lima/resources/:/root/.local/share/lima/resources ghcr.io/aymara/lima:master limaserver
```
with the models installed by lima_models.py in my host  /home/gael/.local/share/lima/resources.
```
❯ python test_lima.py
{
    "tokens": [
        "# sent_id = 1",
        "# text = 然而，这样的处理也衍生了一些问题。",
        "1\t然而\t然而\tADV\t_\t_\t7\tmark\t_\tPos=1|Len=2|SpaceAfter=No",
        "2\t，\t，\tPUNCT\t_\t_\t7\tpunct\t_\tPos=3|Len=1|SpaceAfter=No",
        "3\t这样\t这样\tPRON\t_\t_\t5\tdet\t_\tPos=4|Len=2|SpaceAfter=No",
        "4\t的\t的\tPART\t_\t_\t3\tcase\t_\tPos=6|Len=1|SpaceAfter=No",
        "5\t处理\t处理\tNOUN\t_\t_\t7\tnsubj\t_\tPos=7|Len=2|SpaceAfter=No",
        "6\t也\t也\tADV\t_\t_\t7\tmark\t_\tPos=9|Len=1|SpaceAfter=No",
        "7\t衍生\t衍生\tVERB\t_\t_\t0\troot\t_\tPos=10|Len=2|SpaceAfter=No",
        "8\t了\t了\tPART\t_\t_\t7\tcase\t_\tPos=12|Len=1|SpaceAfter=No",
        "9\t一些\t一些\tADJ\t_\t_\t10\tamod\t_\tPos=13|Len=2|SpaceAfter=No",
        "10\t问题\t问题\tNOUN\t_\t_\t7\tobj\t_\tPos=15|Len=2|SpaceAfter=No",
        "11\t。\t。\tPUNCT\t_\t_\t7\tpunct\t_\tPos=17|Len=1",
        ""
    ]
}
```

**Comment by kleag** [comment]
I have also updated the wiki page to point to the correct docker image and removed the old container from hub.docker.com.

**Comment by Marceau-h** [comment]
Thanks for the help !

By the way, i see that you only mapped the `/root/.local/share/lima/resources, is the other mapping useless ?

**Comment by kleag** [comment]
> Thanks for the help !
> 
> By the way, i see that you only mapped the `/root/.local/share/lima/resources`, is the other mapping useless ?

It can be useful if you want to tweak the configuration by putting there alternative config files. But you can also use environment variables instead.

**Comment by Marceau-h** [comment]
I see, thank you, I'll keep it in case then
