### ISSUE TITLE
Should print plugin login failure message when in error

### ISSUE THREAD

**Issue by kleag** [aymara/lima#164]
**Is your feature request related to a problem? Please describe.**
When a plugin cannot be loaded due to a symbol lookup error, the message is not displayed because it is in debug only while trying to access the system lib.

**Describe the solution you'd like**
If the failure is due to a symbol lookup error, it should be printed anyway. In fact all error messages of all tried paths should be stored and displayed if no method is successful 

This is in `DynamicLibrariesManager.cpp`.

**Comment by benlabbe** [comment]
👏 👏
