### ISSUE TITLE
Should be able to create pipeline at runtime

### ISSUE THREAD

**Issue by kleag** [aymara/lima#168]
**Description**
It's complicated to have to define pipelines in advance in several XML files.

**Solution**
Allow to start with no pipeline, create  one and add pipeline units before starting an analysis.

**Comment by kleag** [comment]
Implemented in fbbcd047ce3add89d8227b23f15c58c5993366b2

Works manually but tests fail.

**Comment by benlabbe** [comment]
Nice progress

**Comment by kleag** [comment]
CI OK too: https://github.com/aymara/lima/actions/runs/9020492739/job/24785768419
