### ISSUE TITLE
Bug with strange characters

### ISSUE THREAD

**Issue by romaricb** [aymara/lima#19]
analyzeText exits with a LinguisticProcessingException on some unusual (but correct) UTF-8 characters, with an error message :
ERROR HypenWordAlternatives : no token forward !

Here is an example of such text (from the Wikipedia page on Navajo language):
----
Les déverbaux peuvent être longs et complexes, par exemple  chidí naaʼnaʼí beeʼeld htsoh bikááʼ dah naaznilígíí " char d'assaut " formé de trois éléments principaux :
* chidí naaʼnaʼí " tracteur à chenilles " formé de chidí  " voiture " + naaʼnaʼí " chenille " ( Ici le suffixe -diin apparaît sous la forme -dįį-. . Les autres nombres se forment en plaçant dóó baʼąą " et en plus de " entre le chiffre des dizaines et celui des unités, par exemple  tádiin dóó baʼąą tʼááłáʼí " trente-et-un " et ashdladiin dóó baʼąą tʼááʼ " cinquante-trois ". On peut également former les numéraux de 41 à 49 de cette manière : " quarante-deux " dízdiin dóó baʼąą naaki ou bien dízdįįnaaki.
----

**Comment by kleag** [comment]
Problem reduced to the following string: `" -dį-"`
A token with unusual utf8 char starting and finishing by a dash.

**Comment by kleag** [comment]
Initial token is OK. The problem appears during hyphen words handling.

**Comment by kleag** [comment]
Corrected in commit 76a6b5e14ca5925bc1e525a4a5fe5d5bc33193b1
