### ISSUE TITLE
Problem with folders and LimaConf environment

### ISSUE THREAD

**Issue by FaizaGara** [aymara/lima#27]
Bug when folder names have accents. LimaConf files are not found.
Unable to open qslog configuration file:
/home/administrateur/Téléchargements/LivraisonMai/Dist/share/config/amose/log4cpp.properties
Configure Problem

**Comment by kleag** [comment]
Cannot reproduce with the current master.
Do you still have the problem ?

**Comment by kleag** [comment]
No answer. Closing.
