### ISSUE TITLE
Enrich the CONLL dumper

### ISSUE THREAD

**Issue by kleag** [aymara/lima#36]
The conll dumper should be enriched to allow the inclusion of  coreference information.

In fact, it  should be configurable to include or not each kind of information.

An option should also allow to output a header line with information on each column.

Thanks to xtannier for his suggestion.

**Comment by benlabbe** [comment]
Update associated to commit d57a26f235:
The CoNLL Dumper is updated to be compliant with CoNLL-U
`# sent_id = <int>` is written as header for each sentence analysis result.

Update associated to commit de7a10f4f5
`# text = <bla bla>` is written as header for each sentence analysis result to be compliant with CoNLL-U

> An option should also allow to output a header line with information on each column.

Update associated to commit 52838987
The new option conllDumper.withColsHeader adds the desired functionnality , with a thrid header line : 
`# cols =  ID	FORM	LEMMA	UPOS	XPOS	FEATS	HEAD	DEPREL	DEPS	MISC`
