### ISSUE TITLE
Possible bug with not handled enumeration switch

### ISSUE THREAD

**Issue by kleag** [aymara/lima#37]
Is it a bug ?
/home/gael/Projets/Amose/amose-install/AMOSE/SourcesLima/lima_linguisticprocessing/tools/automatonCompiler/libautomatonCompiler/recognizerCompiler.cpp:751:12: warning: enumeration value ‘T_ENTITY_GROUP’ not handled in switch [-Wswitch]

Should T_ENTITY_GROUP be handled or  explicitly ignored ?

**Comment by romaricb** [comment]
Code is in deprecated function that has been removed.
