### ISSUE TITLE
Some Characters of Unknown words are deleted in lemma and normalized form 

### ISSUE THREAD

**Issue by FaizaGara** [aymara/lima#40]
Minus characters and digits of unknown words are deleted in normalized forms because the value of unmark and minus of theses characters are empty.

We can resolve this problem by modifying the tokenizerAutomaton-lang.chars.tok file with adding the unmak definition to each character we wan to keep in the normalized form.

For example, in french the following line 
0030, DIGIT ZERO, c_5;
can be modified like
0030, DIGIT ZERO, c_5, u0030;

In this case, the unknown characters are deleted.

**Comment by kleag** [comment]
Commit #814ee44 solves the problem for tokens with digits.

**Comment by kleag** [comment]
Commit #aa0d1bf finish to solve the problem for English too and adds new tva tests.
