### ISSUE TITLE
Problem with automaton and named entity recognition

### ISSUE THREAD

**Issue by Samahh** [aymara/lima#44]
We have some problems with number recognitions due to some changes in automaton code.

While testing only this rule
**Number::@Number:NUMBER:=>NormalizeNumber()** supposed to recognize a serie of two separed numbers as one Specific Entity with NUMBER type.
Lima analyzed this text:
 6 98 88 32 45 44 88 44 88 444 88 110 111 112 223 555 888 777 111 11 12 1 2 

and recognized the following entities that contain more than two numbers:

<entities docid="" offsetNode="0" offset="0">
<entity><pos>1</pos><len>4</len><type>Numex.NUMBER</type><string>6 98</string><components></components><normalization><value> </value><numvalue>0</numvalue><value>6 98</value></normalization></entity>
<entity><pos>1</pos><len>7</len><type>Numex.NUMBER</type><string>6 98 88</string><components></components><normalization><value>  </value><numvalue>88</numvalue><value>6 98 88</value></normalization></entity>
<entity><pos>1</pos><len>10</len><type>Numex.NUMBER</type><string>6 98 88 32</string><components></components><normalization><value>   </value><numvalue>0</numvalue><value>6 98 88 32</value></normalization></entity>
<entity><pos>1</pos><len>13</len><type>Numex.NUMBER</type><string>6 98 88 32 45</string><components></components><normalization><value>    </value><numvalue>45</numvalue><value>6 98 88 32 45</value></normalization></entity>
<entity><pos>1</pos><len>16</len><type>Numex.NUMBER</type><string>6 98 88 32 45 44</string><components></components><normalization><value>     </value><numvalue>0</numvalue><value>6 98 88 32 45 44</value></normalization></entity>
<entity><pos>1</pos><len>19</len><type>Numex.NUMBER</type><string>6 98 88 32 45 44 88</string><components></components><normalization><value>      </value><numvalue>88</numvalue><value>6 98 88 32 45 44 88</value></normalization></entity>
<entity><pos>1</pos><len>22</len><type>Numex.NUMBER</type><string>6 98 88 32 45 44 88 44</string><components></components><normalization><value>       </value><numvalue>0</numvalue><value>6 98 88 32 45 44 88 44</value></normalization></entity>
<entity><pos>1</pos><len>25</len><type>Numex.NUMBER</type><string>6 98 88 32 45 44 88 44 88</string><components></components><normalization><value>        </value><numvalue>88</numvalue><value>6 98 88 32 45 44 88 44 88</value></normalization></entity>
<entity><pos>1</pos><len>29</len><type>Numex.NUMBER</type><string>6 98 88 32 45 44 88 44 88 444</string><components></components><normalization><value>         </value><numvalue>0</numvalue><value>6 98 88 32 45 44 88 44 88 444</value></normalization></entity>
<entity><pos>1</pos><len>32</len><type>Numex.NUMBER</type><string>6 98 88 32 45 44 88 44 88 444 88</string><components></components><normalization><value>          </value><numvalue>88</numvalue><value>6 98 88 32 45 44 88 44 88 444 88</value></normalization></entity>
<entity><pos>1</pos><len>36</len><type>Numex.NUMBER</type><string>6 98 88 32 45 44 88 44 88 444 88 110</string><components></components><normalization><value>           </value><numvalue>0</numvalue><value>6 98 88 32 45 44 88 44 88 444 88 110</value></normalization></entity>
<entity><pos>1</pos><len>40</len><type>Numex.NUMBER</type><string>6 98 88 32 45 44 88 44 88 444 88 110 111</string><components></components><normalization><value>            </value><numvalue>111</numvalue><value>6 98 88 32 45 44 88 44 88 444 88 110 111</value></normalization></entity>
<entity><pos>1</pos><len>44</len><type>Numex.NUMBER</type><string>6 98 88 32 45 44 88 44 88 444 88 110 111 112</string><components></components><normalization><value>             </value><numvalue>0</numvalue><value>6 98 88 32 45 44 88 44 88 444 88 110 111 112</value></normalization></entity>
<entity><pos>1</pos><len>48</len><type>Numex.NUMBER</type><string>6 98 88 32 45 44 88 44 88 444 88 110 111 112 223</string><components></components><normalization><value>              </value><numvalue>223</numvalue><value>6 98 88 32 45 44 88 44 88 444 88 110 111 112 223</value></normalization></entity>
<entity><pos>1</pos><len>52</len><type>Numex.NUMBER</type><string>6 98 88 32 45 44 88 44 88 444 88 110 111 112 223 555</string><components></components><normalization><value>               </value><numvalue>0</numvalue><value>6 98 88 32 45 44 88 44 88 444 88 110 111 112 223 555</value></normalization></entity>
<entity><pos>1</pos><len>56</len><type>Numex.NUMBER</type><string>6 98 88 32 45 44 88 44 88 444 88 110 111 112 223 555 888</string><components></components><normalization><value>                </value><numvalue>888</numvalue><value>6 98 88 32 45 44 88 44 88 444 88 110 111 112 223 555 888</value></normalization></entity>
<entity><pos>1</pos><len>60</len><type>Numex.NUMBER</type><string>6 98 88 32 45 44 88 44 88 444 88 110 111 112 223 555 888 777</string><components></components><normalization><value>                 </value><numvalue>0</numvalue><value>6 98 88 32 45 44 88 44 88 444 88 110 111 112 223 555 888 777</value></normalization></entity>
<entity><pos>1</pos><len>64</len><type>Numex.NUMBER</type><string>6 98 88 32 45 44 88 44 88 444 88 110 111 112 223 555 888 777 111</string><components></components><normalization><value>                  </value><numvalue>111</numvalue><value>6 98 88 32 45 44 88 44 88 444 88 110 111 112 223 555 888 777 111</value></normalization></entity>
<entity><pos>1</pos><len>67</len><type>Numex.NUMBER</type><string>6 98 88 32 45 44 88 44 88 444 88 110 111 112 223 555 888 777 111 11</string><components></components><normalization><value>                   </value><numvalue>0</numvalue><value>6 98 88 32 45 44 88 44 88 444 88 110 111 112 223 555 888 777 111 11</value></normalization></entity>
<entity><pos>1</pos><len>70</len><type>Numex.NUMBER</type><string>6 98 88 32 45 44 88 44 88 444 88 110 111 112 223 555 888 777 111 11 12</string><components></components><normalization><value>                    </value><numvalue>12</numvalue><value>6 98 88 32 45 44 88 44 88 444 88 110 111 112 223 555 888 777 111 11 12</value></normalization></entity>
<entity><pos>1</pos><len>72</len><type>Numex.NUMBER</type><string>6 98 88 32 45 44 88 44 88 444 88 110 111 112 223 555 888 777 111 11 12 1</string><components></components><normalization><value>                     </value><numvalue>0</numvalue><value>6 98 88 32 45 44 88 44 88 444 88 110 111 112 223 555 888 777 111 11 12 1</value></normalization></entity>
<entity><pos>1</pos><len>74</len><type>Numex.NUMBER</type><string>6 98 88 32 45 44 88 44 88 444 88 110 111 112 223 555 888 777 111 11 12 1 2</string><components></components><normalization><value>                      </value><numvalue>2</numvalue><value>6 98 88 32 45 44 88 44 88 444 88 110 111 112 223 555 888 777 111 11 12 1 2</value></normalization></entity>
</entities>

@Number=(
t_comma_number,t_dot_number,t_integer,
deux$NC,
trois$NC,
quatre$NC,
cinq$NC,
six$NC,
sept$NC,
huit$NC,
neuf$NC,
dix$NC,
onze$NC,
douze$NC,
treize$NC,
quatorze$NC,
quinze$NC,
seize$NC,
dix-sept$NC,
dix-huit$NC,
dix-neuf$NC,
vingt$NC,
vingts$NC,
vingt-deux$NC,
vingt-trois$NC,
vingt-quatre$NC,
vingt-cinq$NC,
vingt-six$NC,
vingt-sept$NC,
vingt-huit$NC,
vingt-neuf$NC,
trente$NC,
trente-deux$NC,
trente-trois$NC,
trente-quatre$NC,
trente-cinq$NC,
trente-six$NC,
trente-sept$NC,
trente-huit$NC,
trente-neuf$NC,
quarante$NC,
quarante-deux$NC,
quarante-trois$NC,
quarante-quatre$NC,
quarante-cinq$NC,
quarante-six$NC,
quarante-sept$NC,
quarante-huit$NC,
quarante-neuf$NC,
cinquante$NC,
cinquante-deux$NC,
cinquante-trois$NC,
cinquante-quatre$NC,
cinquante-cinq$NC,
cinquante-six$NC,
cinquante-sept$NC,
cinquante-huit$NC,
cinquante-neuf$NC,
soixante$NC,
soixante-deux$NC,
soixante-trois$NC,
soixante-quatre$NC,

soixante-cinq$NC,
soixante-six$NC,
soixante-sept$NC,
soixante-huit$NC,
soixante-neuf$NC,
septante$NC,
septante-deux$NC,
septante-trois$NC,
septante-quatre$NC,
septante-cinq$NC,
septante-six$NC,
septante-sept$NC,
septante-huit$NC,
septante-neuf$NC,
soixante-dix$NC,
soixante-douze$NC,
soixante-treize$NC,
soixante-quatorze$NC,
soixante-quinze$NC,
soixante-seize$NC,
soixante-dix-sept$NC,
soixante-dix-huit$NC,
soixante-dix-neuf$NC,
huitante$NC,
huitante-deux$NC,
huitante-trois$NC,
huitante-quatre$NC,
huitante-cinq$NC,
huitante-six$NC,
huitante-sept$NC,
huitante-huit$NC,
huitante-neuf$NC,
octante$NC,
octante-deux$NC,
octante-trois$NC,
octante-quatre$NC,
octante-cinq$NC,
octante-six$NC,
octante-sept$NC,
octante-huit$NC,
octante-neuf$NC,
quatre-vingt$NC,
quatre-vingts$NC,
quatre-vingt-un$NC,
quatre-vingt-deux$NC,
quatre-vingt-trois$NC,
quatre-vingt-quatre$NC,
quatre-vingt-cinq$NC,
quatre-vingt-six$NC,
quatre-vingt-sept$NC,
quatre-vingt-huit$NC,
quatre-vingt-neuf$NC,
nonante$NC,
nonante-deux$NC,
nonante-trois$NC,
nonante-quatre$NC,
nonante-cinq$NC,
nonante-six$NC,
nonante-sept$NC,
nonante-huit$NC,
nonante-neuf$NC,
quatre-vingt-dix$NC,
quatre-vingt-onze$NC,
quatre-vingt-douze$NC,
quatre-vingt-treize$NC,
quatre-vingt-quatorze$NC,
quatre-vingt-quinze$NC,
quatre-vingt-seize$NC,
quatre-vingt-dix-sept$NC,
quatre-vingt-dix-huit$NC,
quatre-vingt-dix-neuf$NC,
cent$NC,
cents$NC,
mille$NC
)

@OrdNumber=(
billionième$NC,
centième$NC,
cinquantième$NC,
cinquième$NC,
deuxième$NC,
dixième$NC,
douzième$NC,
huitantième$NC,
huitième$NC,
milliardième$NC,ecificEntities/NUMBER-fre.bin
millionième$NC,
millième$NC,
neuvième$NC,
onzième$NC,
premier$NC,
quarantième$NC,
quatorzième$NC,
quatre-vingtième$NC,
quatrième$NC,
quinzième$NC,
seizième$NC,
septantième$NC,
septième$NC,
sixième$NC,
soixantième$NC,
ter$NC,
treizième$NC,
trentième$NC,
trillionème$NC,
troisième$NC,
unième$NC,
vingtième$NC
)

**Comment by romaricb** [comment]
The problem is that when a specific entity is created, the rules are applied to the rest of the text **starting from the newly created node** instead of starting from the following node(s). Here, the rule first creates an entity "6 98", then this entity is a number and followed by a number "88", thus a new entity "6 98 88" is created etc.
This can be corrected by restarting the application of the rules from the nodes after the newly created node. Before making this correction, we need to make sure this feature is not used in other process units that use the rules, such as syntactic analysis.

**Comment by kleag** [comment]
Here is what we currently obtain:
[test-fre132.txt.se.xml.txt](https://github.com/aymara/lima/files/543954/test-fre132.txt.se.xml.txt)

Is it the wanted behavior ? If yes, this issue should be closed. Otherwise, we should update it.
