### ISSUE TITLE
Problem with automaton (out of range recognition)

### ISSUE THREAD

**Issue by Samahh** [aymara/lima#45]
This rule
  @Number:(+|-)?:@Number{0-3} \%?:NUMBER:=>NormalizeNumber()
is supposed to concatenate at least a series of 4 numbers and tag them as an entity NUMBER.

When LIMA analyses this example of text: 6 98 88 55 45 42 15. It concatenates all this sequence (a series of 7 numbers) as an entity NUMBER.

We should normally have two entities:
 6 98 88 55
 45 42 15

There is a bug in the automaton.

**Comment by romaricb** [comment]
This is the same issue as #44.
