### ISSUE TITLE
Problem with lemmas of certain dates in the CoNLL output format  

### ISSUE THREAD

**Issue by osf9018** [aymara/lima#46]
In the test-conll.txt file, the 25th token of the third sentence has <9 octobre> as form and < octobre> as lemma. The number of the date, actually identified as a date entity by LIMA, has disappeared in the lemma.

[test.txt](https://github.com/aymara/lima/files/393201/test.txt)
[test-conll.txt](https://github.com/aymara/lima/files/393205/test-conll.txt)

**Comment by kleag** [comment]
This seems to have been solved   in recent work on dates.
Attached is the output I get.
[test-fre131.txt.conll.txt](https://github.com/aymara/lima/files/543940/test-fre131.txt.conll.txt)
