### ISSUE TITLE
Segmentation fault for a file containing only a dot

### ISSUE THREAD

**Issue by osf9018** [aymara/lima#54]
analyzeText -l eng test.txt
or 
analyzeText -l fre test.txt

with test.txt, a file containing only a dot (with or without a newline), causes a segmentation fault error.

**Comment by kleag** [comment]
With which version of LIMA and which configuration ? With latest version and default configuration, this does not happen.
This could be related to commits:
commit 22907c3
Author: Gael de Chalendar <gael.de-chalendar@cea.fr>
Date:   Thu Jun 9 16:28:33 2016 +0200

    Do not crash in case of empty graph

commit bee4ddc
Author: Gael de Chalendar <gael.de-chalendar@cea.fr>
Date:   Mon May 2 10:52:16 2016 +0200

    Avoid a crash when there is no sentence to dump

commit 24de3f5
Author: Gael de Chalendar <gael.de-chalendar@cea.fr>
Date:   Thu May 21 09:00:57 2015 +0200

    Avoid a crash in case of empty morph data

**Comment by kleag** [comment]
No answer to feedback demand. Closing.
