### ISSUE TITLE
classe CharChart : il manque la catégorie unicode "NoCategory"

### ISSUE THREAD

**Issue by fwantinno** [aymara/lima#56]
La méthode QChar::category() renvoit un indice qui permet de déterminer le libellé de la catégory unicode du caractère via le vecteur m_unicodeCategories.
Problème : les indices sont décalés de 1 du fait qu'il manque la catégorie "NoCategory".
La méthode const CharClass* CharChart::charClass (const LimaChar& c) const donne un résultat erroné.
Solution : ajouter la catégorie manquante.
```
m_unicodeCategories
  << "NoCategory"           <----- AJOUT catégorie manquante
  << "Mark_NonSpacing"
  << "Mark_SpacingCombining"
  << "Mark_Enclosing"
  << "Number_DecimalDigit"
  << "Number_Letter"
  << "Number_Other"
  << "Separator_Space"
  << "Separator_Line"
  << "Separator_Paragraph"
  << "Other_Control"
  << "Other_Format"
  << "Other_Surrogate"
  << "Other_PrivateUse"
  << "Other_NotAssigned"
  << "Letter_Uppercase"
  << "Letter_Lowercase"
  << "Letter_Titlecase"
  << "Letter_Modifier"
  << "Letter_Other"
  << "Punctuation_Connector"
  << "Punctuation_Dash"
  << "Punctuation_Open"
  << "Punctuation_Close"
  << "Punctuation_InitialQuote"
  << "Punctuation_FinalQuote"
  << "Punctuation_Other"
  << "Symbol_Math"
  << "Symbol_Currency"
  << "Symbol_Modifier"
  << "Symbol_Other";
```

**Comment by kleag** [comment]
In fact categories definitions changed between Qt4 and Qt5. It started at 1 in Qt4 (http://doc.qt.io/qt-4.8/qchar.html#Category-enum) and it now starts at 0 (http://doc.qt.io/qt-5.8/qchar.html#Category-enum)

As LIMA is again (temporarily) supported on Qt4, I will add a check to adapt LIMA behaviour depending on Qt version.

@simonmarchal , I'll do the change on master and open a pull request for the branch.

**Comment by kleag** [comment]
@simonmarchal, I changed my mind and did cherry-picking to apply the correction to the Lima-antinno-integration branch.
