### ISSUE TITLE
Lima Server silently ignore port opening error

### ISSUE THREAD

**Issue by kleag** [aymara/lima#65]
In LimaServer.cpp, lines 129 and 133, return values should be checked in order to cleanly handle errors:
  m_server->listen(QHostAddress::Any, port);

**Comment by benlabbe** [comment]
fixed in commit 94501ea66e1

**Comment by benlabbe** [comment]
The previously mentioned fix is buggy.
The server does not startup.

**Comment by benlabbe** [comment]
Commit 569f5433a from 2019-07-19 now fixes the issue without side effects.
