### ISSUE TITLE
Inconsistency between Modex documentation and rules compiler behavior

### ISSUE THREAD

**Issue by kleag** [aymara/lima#66]
Modex documentation states that "Sometimes, one wants to use some tokens in the rules because they are useful to indicate a context but they must not be part of the recognised expression. This is indicated vy surrounding these portions of expressions by brackets [...]. These brackets can be placed around single units or complex expressions." (https://github.com/aymara/lima/wiki/Modex-Rules-Format#boundaries-of-the-expression).

But this rule:
`@Particule:[@Title @Firstname]:(@Particule|@PersonNamePart){1-n}:LAST_NAME:`
causes the following error:
```
 : Automaton::Compiler : 2018-07-12T11:09:54.412 ERROR 0x1cf1d20 Error file  GIVEN_NAMES-fre.rules , line  26 :  got confused while reading expression [@Title 
 : Automaton::Compiler : 2018-07-12T11:09:54.412 ERROR 0x1cf1d20 in rule:  @Particule:[@Title @Firstname]:(@Particule|@PersonNamePart){1-n}:LAST_NAME: 
```

This is inconsistent.

**Comment by romaricb** [comment]
In case a complex expression, the whole expression must be enclosed in parentheses
```
@Particule:[(@Title @Firstname)]:(@Particule|@PersonNamePart){1-n}:LAST_NAME:
```
I corrected the docs to be more clear.
