### ISSUE TITLE
QCoreApplication does not forward exit_codes in analyzeText

### ISSUE THREAD

**Issue by benlabbe** [aymara/lima#75]
In ``lima_linguisticprocessing/test/analyzeText.cpp`` , the ``QCoreApplication`` is configured to the execute the ``run()`` method through the use of  ``QObject::connect()``  with ``SIGNAL`` and ``SLOT`` .

This behavior avoids the forwarding of the exit codes in ``run`` to the linux console.

The exit codes proposed [hitherto](https://github.com/aymara/lima/blob/fb48a250bd47a51f2f6c40cd05837ebcdefa4cdb/lima_linguisticprocessing/test/analyzeText.cpp) express different semantics :
- correct ends of processus : ``return SUCCESS_ID;`` at [line 456](https://github.com/aymara/lima/blob/fb48a250bd47a51f2f6c40cd05837ebcdefa4cdb/lima_linguisticprocessing/test/analyzeText.cpp#L456)
-  mis-configuration : ``return EXIT_FAILURE;`` at [line 295](https://github.com/aymara/lima/blob/fb48a250bd47a51f2f6c40cd05837ebcdefa4cdb/lima_linguisticprocessing/test/analyzeText.cpp#L295)
-  mis-configuration of language : ``return 1;`` at [line 217](https://github.com/aymara/lima/blob/fb48a250bd47a51f2f6c40cd05837ebcdefa4cdb/lima_linguisticprocessing/test/analyzeText.cpp#L217)

These exit codes would have a high value to insert analyzeText in a production environment where for exemple the document language is configured on the fly by the end-user.

As far as I can remember, the user specification of a non-supported language might even raise a non-catched exception and result into a Qt termination of the process , a dump of the exception in stderr, and an exit_code of 137.

I think this kind of exception should be handled by analyzeText with a proper abortion, error message in stderr & logs , and exit code.

**Comment by kleag** [comment]
The return value problem is corrected in commit 4c13bef091fbcd3ce4ff18068ddfd4eb0397ea58.

The unhandled exception is another problem. please open another issue.
