### ISSUE TITLE
Problem with ConllDumper under windows

### ISSUE THREAD

**Issue by laleye** [aymara/lima#79]
Failed to execute analyzeText.exe -l fre filename. The following errors appear even in server mode operation.

 : Common::AbstractFactoryPattern : 2018-11-09T13:06:00.198 ERROR 0x1d701fbe3a0 DynamicLibrariesManager::loadLibrary() -
-  Failed to open lib  "Cannot load library lima-lp-analysisdumpers: Le module spÚcifiÚ est introuvable."
 : Common::AbstractFactoryPattern : 2018-11-09T13:06:00.222 ERROR 0x1d701fbe3a0 DynamicLibrariesManager::loadLibrary() -
-  Failed to open lib  "Cannot load library lima-lp-semanticanalysis: Le module spÚcifiÚ est introuvable."
2: No AbstractFactory for classId 'ConllDumper' !
   Main factory (this) is: 00007FFD20CB0000
   Should be initialized at library loading time.
   Maybe you forgot to link with the library defining this classId ?
   Or you forgot to define it as a plugin using, in its CMakeLists.txt,
   DECLARE_LIMA_PLUGIN, instead of add_library ?

**Comment by kleag** [comment]
The problem comes from the fact that the dll python34.dll is not included in LIMA packages. Thus the library lima-lp-analysisdumpers which contains the plugin ConllDumper fails to link. The plugin is reported as absent.
There is two problems:
- the absent dll;
- the misleading message pointing to the wrong problem.

**Comment by victorbocharov** [comment]
@laleye please check this version:
https://github.com/aymara/lima/releases/tag/20181113154556-44dac127

**Comment by laleye** [comment]
> @laleye please check this version:
> https://github.com/aymara/lima/releases/tag/20181113154556-44dac127

The same error previously mentioned occurs.

**Comment by victorbocharov** [comment]
Qt and python34.dll require their own versions of UCRT.

**Comment by victorbocharov** [comment]
@laleye please check again this version:
https://github.com/aymara/lima/releases/tag/20181115100545-1fd356bc

**Comment by laleye** [comment]
@victorbocharov  This version works when I use analyzeText but nothing happens with the server mode. limaserver command does not work and does not return an error

**Comment by victorbocharov** [comment]
qhttpserver.dll was missing.
@laleye version https://github.com/aymara/lima/releases/tag/20181115190016-0b76195c should work.

**Comment by kleag** [comment]
@laleye could you reopen if it's not OK in fact?
Thanks.
