### ISSUE TITLE
Idiomatic expressions building is broken: idioms PoS are not set

### ISSUE THREAD

**Issue by kleag** [aymara/lima#82]
**Describe the bug**
Idiomatic expressions building is broken. 

**To Reproduce**
1. Go to 'https://travis-ci.org/aymara/lima/jobs/479302300#L7890'
2. See error

Furthermore, if you check the idioms tests XML output, you will see that idiom tokens PoS are not set (empty).

**Expected behavior**
Idioms should have tokens and tva tests should succeed.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 18.04
 - Version [e.g. 22] current master

**Comment by victorbocharov** [comment]
Fixed in fd3d548bb0290308884f2dfda1f298dc53c599b2
