### ISSUE TITLE
Set the number of threads in gbuild.sh

### ISSUE THREAD

**Issue by benlabbe** [aymara/lima#85]
Could it be possible to set from the command line the number of threads used while building Lima.

The ``-j`` option is not available for ``gbuild.sh``, and the default value passed to make/ninja is currently the maximal num of threads on the building host (ie ``grep ^processor -c /proc/cpuinfo``)

**Comment by kleag** [comment]
Sure. You are welcome to add this feature.

**Comment by benlabbe** [comment]
Implemented in gbuild.sh and gbuild-clang.sh since commit 146e2f054077
