### ISSUE TITLE
Deep Lima : provide the list of 3 letters ISO639-3 language code

### ISSUE THREAD

**Issue by benlabbe** [aymara/lima#97]
It is hard to identify the available languages in Deep Lima, and how to set them in analyzeText since they are not listed with their respective code.

The Deep Lima evaluation page should list the exact  3 letters ISO639-3 language codes per available language .

https://github.com/aymara/lima/wiki/DeepLima-evaluation

**Comment by victorbocharov** [comment]
done

**Comment by kleag** [comment]
This should also be available as a table in the main Deep LIMA page with language, corpus name, iso code and link to the deb file.
Also, the iso code to use a runtime should be included in the deb filename.

**Comment by victorbocharov** [comment]
File names now include iso code and language name.
Table has direct links to packages: https://github.com/aymara/lima-models/blob/master/eval.md

**Comment by benlabbe** [comment]
Great work @victorbocharov . Thank you.
