### ISSUE TITLE
SpecificEntities in Portugese

### ISSUE THREAD

**Issue by benlabbe** [aymara/lima#99]
There is no linguisticData available to build rule-based NamedEntity Recognition rules in Portugese.

**Comment by kleag** [comment]
Since 27556d2bcd58c5ae4328a8a64f3113d380a08af7, named entities work with UD languages and can be specialized with each of them. I don't think it is still useful to develop resources for the legacy por resources.
What do you think?

**Comment by kleag** [comment]
Fill free to reopen if needed.
